### ISSUE TITLE
Errors when logging in for the first time on dev_appserver

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#102]
```
What steps will reproduce the problem?
1. Install micolog
2. Go to http://localhost:8080/
3. Go to http://localhost:8080/
3. Click Login

What is the expected output? What do you see instead?
I expected to see a form/screen to enter my username and password, or to 
register for the blog.
Instead, I see the error message below. 
When I upload the application, so I can run it on GAE, I get the Google App 
Engine login screen.

What version of the product are you using? On what operating system?
0.7RC on Ubuntu Linux 10.1

Please provide any additional information below.
--> --> -->
Traceback (most recent call last):
  File "/home/michael/mycode/google_appengine/google/appengine/tools/dev_appserver.py", line 3206, in _HandleRequest
    self._Dispatch(dispatcher, self.rfile, outfile, env_dict)
  File "/home/michael/mycode/google_appengine/google/appengine/tools/dev_appserver.py", line 3149, in _Dispatch
    base_env_dict=env_dict)
  File "/home/michael/mycode/google_appengine/google/appengine/tools/dev_appserver.py", line 525, in Dispatch
    base_env_dict=base_env_dict)
  File "/home/michael/mycode/google_appengine/google/appengine/tools/dev_appserver.py", line 2450, in Dispatch
    CGIDispatcher.Dispatch(self, *args, **kwargs)
  File "/home/michael/mycode/google_appengine/google/appengine/tools/dev_appserver.py", line 2402, in Dispatch
    self._module_dict)
  File "/home/michael/mycode/google_appengine/google/appengine/tools/dev_appserver.py", line 2439, in curried_exec_cgi
    return ExecuteCGI(*args, **kwargs)
  File "/home/michael/mycode/google_appengine/google/appengine/tools/dev_appserver.py", line 2310, in ExecuteCGI
    logging.debug('Executing CGI with env:\n%s', pprint.pformat(env))
  File "/usr/lib/python2.6/pprint.py", line 60, in pformat
    return PrettyPrinter(indent=indent, width=width, depth=depth).pformat(object)
  File "/usr/lib/python2.6/pprint.py", line 119, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/lib/python2.6/pprint.py", line 137, in _format
    rep = self._repr(object, context, level - 1)
  File "/usr/lib/python2.6/pprint.py", line 230, in _repr
    self._depth, level)
  File "/usr/lib/python2.6/pprint.py", line 242, in format
    return _safe_repr(object, context, maxlevels, level)
  File "/usr/lib/python2.6/pprint.py", line 284, in _safe_repr
    for k, v in _sorted(object.items()):
  File "/usr/lib/python2.6/pprint.py", line 75, in _sorted
    with warnings.catch_warnings():
  File "/usr/lib/python2.6/warnings.py", line 333, in __init__
    self._module = sys.modules['warnings'] if module is None else module
KeyError: 'warnings'

```

Original issue reported on code.google.com by `michael....@gmail.com` on 10 Oct 2010 at 10:53

**Comment by GoogleCodeExporter** [comment]
```
遇到了和上面同样的问题，(micoblog 0.7 release, Ubuntu 10.10)
```

Original comment by `Dreamer...@gmail.com` on 13 Oct 2010 at 6:47

**Comment by GoogleCodeExporter** [comment]
```
安装Python 2.5吧
```

Original comment by `hongwei....@gmail.com` on 13 Oct 2010 at 7:21

**Comment by GoogleCodeExporter** [comment]
```
遇到一样的问题，win7，难道是python2.7的原因吗？
```

Original comment by `yim...@gmail.com` on 15 Oct 2010 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
如果是本地测试，又不想装python2.5的话可以将
"/home/michael/mycode/google_appengine/google/appengine/tools/dev_appserver.py",
 line 2310  logging.debug('Executing CGI with env:\n%s', pprint.pformat(env))
注释掉，博客程序上传到app engine后是正常的

```

Original comment by `Dreamer...@gmail.com` on 15 Oct 2010 at 4:42
