### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#105]
```
版本0.736

我下载其他的主题，都出错，
只有default主题不出错。

错误信息：
pydev debugger: starting
INFO     2010-10-15 11:26:23,766 appengine_rpc.py:153] Server: 
appengine.google.com
INFO     2010-10-15 11:26:23,786 appcfg.py:414] Checking for updates to the SDK.
INFO     2010-10-15 11:26:25,505 appcfg.py:428] The SDK is up to date.
INFO     2010-10-15 11:26:27,569 dev_appserver_main.py:443] Running application 
cleocn on port 8080: http://localhost:8080
INFO     2010-10-15 11:26:34,447 model.py:14] module base reloaded
WARNING  2010-10-15 11:26:34,535 dev_appserver.py:1171] Blocking access to 
skipped file "g:\eclipse\workspace\micolog7\src\plugins\googleanalytics.pyc"
INFO     2010-10-15 11:26:34,589 base.py:28] module base reloaded
WARNING  2010-10-15 11:26:34,686 dev_appserver.py:1171] Blocking access to 
skipped file "g:\eclipse\workspace\micolog7\src\plugins\__init__.pyc"
ERROR    2010-10-15 11:28:32,851 __init__.py:391] expected string or buffer
Traceback (most recent call last):
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\ext\webapp\__init__.py", line 511, in __call__
    handler.get(*groups)
  File "G:\Eclipse\workspace\micolog7\src\blog.py", line 102, in get
    self.doget(page)
  File "G:\Eclipse\workspace\micolog7\src\base.py", line 91, in _wrapper
    method(*args, **kwargs)
  File "G:\Eclipse\workspace\micolog7\src\blog.py", line 139, in doget
    'postscount':entrycount
  File "G:\Eclipse\workspace\micolog7\src\base.py", line 336, in render
    html=self.get_render(template_file,values)
  File "G:\Eclipse\workspace\micolog7\src\base.py", line 324, in get_render
    html = micolog_template.render(self.blog.theme, template_file, self.template_vals)
  File "G:\Eclipse\workspace\micolog7\src\micolog_template.py", line 81, in render
    t = load(theme,template_file, debug)
  File "G:\Eclipse\workspace\micolog7\src\micolog_template.py", line 116, in load
    template = django.template.loader.get_template(template_file)
  File "D:\Program Files (x86)\Google\google_appengine\lib\django\django\template\loader.py", line 80, in get_template
    template = get_template_from_string(source, origin, template_name)
  File "D:\Program Files (x86)\Google\google_appengine\lib\django\django\template\loader.py", line 88, in get_template_from_string
    return Template(source, origin, name)
  File "D:\Program Files (x86)\Google\google_appengine\lib\django\django\template\__init__.py", line 158, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "D:\Program Files (x86)\Google\google_appengine\lib\django\django\template\__init__.py", line 173, in compile_string
    parser = parser_factory(lexer.tokenize())
  File "D:\Program Files (x86)\Google\google_appengine\lib\django\django\template\__init__.py", line 197, in tokenize
    bits = filter(None, tag_re.split(self.template_string))
TypeError: expected string or buffer
INFO     2010-10-15 11:28:32,917 dev_appserver.py:3283] "GET / HTTP/1.1" 500 -
INFO     2010-10-15 11:28:33,219 dev_appserver_index.py:212] Updating 
G:\Eclipse\workspace\micolog7\src\index.yaml


```

Original issue reported on code.google.com by `cle...@gmail.com` on 15 Oct 2010 at 3:37

**Comment by GoogleCodeExporter** [comment]
```
我也是换了主题就出错
```

Original comment by `spf5...@gmail.com` on 27 Feb 2011 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
参见 http://bbs.xuming.net/t/417

症状： 
1.首页由之前的404变成以上的错误提示； 
2.可以进入后台管理； 

更新：进入admin/setup 后点选 允许 
Trackback/Pingback之后，更新缓存，成功。问题解决。
我的解决了
```

Original comment by `spf5...@gmail.com` on 27 Feb 2011 at 7:23

**Comment by GoogleCodeExporter** [comment]
```
thanks ... solved my issue ...
```

Original comment by `nikeshha...@gmail.com` on 9 Jun 2011 at 8:56
