### ISSUE TITLE
添加ssl模块的悲剧

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#107]
```
现在新版本上传提示这些内容？

1.2010-10-19 14:03:22,687 WARNING appengine_rpc.py:405 ssl module not found.
Without the ssl module, the identity of the remote host cannot be verified, 
and.....
2.AttributeError: 'module' object has no attribute 'HTTPSHandler'

原来直接装python2.5没说什么SSL模块的问题呀？

网上找到两种办法
1.下载mingw编译器及相关环境编译安装SSL模块
http://zzfei.com/gae-python-ssl/
http://www.marguin.info/tag/gae
2.安装Activestate的Python 
2.7版本，这个版本是安装后就已经带有ssl模块了
http://vanniszsu.blogbus.com/logs/73189397.html

第一种教程太高科技看不懂 第二种还是没成功...
倒是我把python、GAE 
Launcher卸载了，用SDupload上传到一个新的Google App 
ID成功了，不过原来的Google App ID还是不得行... 

2010-10-19 17:22:54 Running command: "['C:\\Python27\\pythonw27.exe', '-u', 
'C:\\Program Files\\Google\\google_appengine\\appcfg.py', '--no_cookies', 
u'--email=####@gmail.com', '--passin', 'update', 'D:\\SDUpload\\micolog']"
Traceback (most recent call last):
  File "C:\Program Files\Google\google_appengine\appcfg.py", line 69, in <module>
    run_file(__file__, globals())
  File "C:\Program Files\Google\google_appengine\appcfg.py", line 65, in run_file
    execfile(script_path, globals_)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 63, in <module>
    from google.appengine.tools import appengine_rpc
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appengine_rpc.py", line 24, in <module>
    import fancy_urllib
  File "C:\Program Files\Google\google_appengine\lib\fancy_urllib\fancy_urllib\__init__.py", line 333, in <module>
    class FancyHTTPSHandler(urllib2.HTTPSHandler):
AttributeError: 'module' object has no attribute 'HTTPSHandler'
2010-10-19 17:22:55 (Process exited with code 1)

You can close this window now.

```

Original issue reported on code.google.com by `lcc...@gmail.com` on 19 Oct 2010 at 9:24

**Comment by GoogleCodeExporter** [comment]
```
Another transaction by user lccgoo is already in progress for this app and 
major version. That user can undo the transaction with appcfg.py's "rollback" 
command.

是嘛意思啊？
```

Original comment by `lcc...@gmail.com` on 19 Oct 2010 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
把micolog改个名字 再上传
实战经验！！
```

Original comment by `lcc...@gmail.com` on 25 Oct 2010 at 1:02

**Comment by GoogleCodeExporter** [comment]
```
http://eric.cloud-mes.com/2011/09/10/python_2.5_SSL_1.15_module_for_GAE.html
用我的exe文件SSL安装吧……
```

Original comment by `eric.gu...@gmail.com` on 12 Sep 2011 at 5:44
