### ISSUE TITLE
升级造成的Error 500

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#108]
```
从128 升级到155 出现以下悲剧。切回128有正常了。
为什么？

Error 500
Sorry, the server encountered an error. We have logged this error and will look 
into it.
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 511, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/yzm-blog/155.345679136002930019/base.py", line 115, in _wrapper
    method(*args, **kwargs)
  File "/base/data/home/apps/yzm-blog/155.345679136002930019/blog.py", line 227, in get
    comments=entry.get_comments_by_page(mp,self.blog.comments_per_page)
  File "/base/data/home/apps/yzm-blog/155.345679136002930019/model.py", line 516, in get_comments_by_page
    return self.purecomments().fetch(psize,offset = (index-1) * psize)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 1849, in fetch
    raw = raw_query.Get(limit, offset, rpc=rpc)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/api/datastore.py", line 1269, in Get
    limit=limit, offset=offset, prefetch_count=limit, **kwargs)._Get(limit)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/api/datastore.py", line 1178, in _Run
    rpc=rpc)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/api/datastore.py", line 1211, in _RunInternal
    str(exc) + '\nThis query needs this index:\n' + yaml)
NeedIndexError: The index for this query is not ready to serve. See the 
Datastore Indexes page in the Admin Console.
This query needs this index:
- kind: Comment
  properties:
  - name: ctype
  - name: entry
  - name: date

```

Original issue reported on code.google.com by `yuzeming` on 22 Oct 2010 at 1:58

**Comment by GoogleCodeExporter** [comment]
```
你要等待索引建立完成后才能使用啊
NeedIndexError: The index for this query is not ready to serve. See the 
Datastore Indexes page in the Admin Console.
This query needs this index:
- kind: Comment
  properties:
  - name: ctype
  - name: entry
  - name: date


```

Original comment by `hongwei....@gmail.com` on 23 Oct 2010 at 3:53

**Comment by GoogleCodeExporter** [comment]
```
是的，我更新了N次以后正常了。
```

Original comment by `yuzeming` on 23 Oct 2010 at 12:25
