### ISSUE TITLE
不能上传

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#114]
```

2010-11-07 15:19:36,723 ERROR appcfg.py:1818 An unexpected error occurred. 
Aborting. 
Traceback (most recent call last):
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 1784, in DoUpload
    missing_files = self.Begin()
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 1528, in Begin
    version=self.version, payload=self.config.ToYAML())
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/home/alex/.application/tools/google_appengine/lib/fancy_urllib/fancy_urllib/__init__.py", line 359, in do_open
    raise url_error
URLError: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/home/alex/.application/tools/google_appengine/appcfg.py", line 69, in <module>
    run_file(__file__, globals())
  File "/home/alex/.application/tools/google_appengine/appcfg.py", line 65, in run_file
    execfile(script_path, globals_)
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 3100, in <module>
    main(sys.argv)
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 3091, in main
    result = AppCfgApp(argv).Run()
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 2013, in Run
    self.action(self)
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 2943, in __call__
    return method()
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 2368, in Update
    lambda path: open(os.path.join(basepath, path), 'rb'))
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 1784, in DoUpload
    missing_files = self.Begin()
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appcfg.py", line 1528, in Begin
    version=self.version, payload=self.config.ToYAML())
  File "/home/alex/.application/tools/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/home/alex/.application/tools/google_appengine/lib/fancy_urllib/fancy_urllib/__init__.py", line 359, in do_open
    raise url_error
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
[alex@localhost config]$ 
```

Original issue reported on code.google.com by `alex.y...@gmail.com` on 7 Nov 2010 at 7:25

**Comment by GoogleCodeExporter** [comment]
```
app.yaml改过了吗？
```

Original comment by `hongwei....@gmail.com` on 7 Nov 2010 at 11:49

**Comment by GoogleCodeExporter** [comment]
```
改过
```

Original comment by `alex.y...@gmail.com` on 8 Nov 2010 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
不知是不是 python 2.7 for Linux　版本的问题.还是最新的 
appengine问题.我是在linux上
```

Original comment by `alex.y...@gmail.com` on 8 Nov 2010 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
哈哈搞定了我在 copy 
applicationName　时多了一个空格.(唉总是犯低级错误.)
```

Original comment by `alex.y...@gmail.com` on 8 Nov 2010 at 9:11
