### ISSUE TITLE
在服务器上发表文章出错

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#127]
```
这是错误代码
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 702, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/ansenbbs/10.351548479192506117/base.py", line 51, in wrapper
    return method(self, *args, **kwargs)
  File "/base/data/home/apps/ansenbbs/10.351548479192506117/admin.py", line 522, in post
    newcates.append(Category.all().order('date')[0].key())
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2149, in __getitem__
    raise IndexError('The query returned fewer than %d results' % (arg+1))
IndexError: The query returned fewer than 1 results

```

Original issue reported on code.google.com by `shen...@ansen.me` on 2 Jul 2011 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
你用的不是最新版吧，请下载这里的最新版或使用svn工具
```

Original comment by `ad...@wer.pp.ru` on 2 Jul 2011 at 5:03
