### ISSUE TITLE
上传后出以下错误

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#13]
```
#

1.
      08-21 10:38PM 32.702 / 500 46ms 73cpu_ms 36api_cpu_ms 0kb Mozilla/5.0
(Windows; U; Windows NT 5.1; zh-CN; rv:1.9.1.2) Gecko/20090729
Firefox/3.5.2,gzip(gfe)
      See details

      61.153.14.34 - - [21/Aug/2009:22:38:32 -0700] "GET / HTTP/1.1" 500
120 - "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9.1.2)
Gecko/20090729 Firefox/3.5.2,gzip(gfe)" "alvin-blog.appspot.com"

2.
      D 08-21 10:38PM 32.736


path:/base/data/home/apps/alvin-blog/1.335791118718401552/themes/default/templat
es/error500.html

3.
      D 08-21 10:38PM 32.736


path:/base/data/home/apps/alvin-blog/1.335791118718401552/themes/default/templat
es/error.html

   4.
      E 08-21 10:38PM 32.739

      Traceback (most recent call last):

   5.
      E 08-21 10:38PM 32.739

        File "/base/python_dist/lib/python2.5/wsgiref/handlers.py", line
92, in run

   6.
      E 08-21 10:38PM 32.740

          self.result = application(self.environ, self.start_response)

   7.
      E 08-21 10:38PM 32.740

        File
"/base/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line
523, in __call__

   8.
      E 08-21 10:38PM 32.741

          handler.handle_exception(e, self.__debug)

   9.
      E 08-21 10:38PM 32.741

        File
"/base/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line
387, in handle_exception

  10.
      E 08-21 10:38PM 32.741

          self.error(500)

  11.
      E 08-21 10:38PM 32.741

        File
"/base/data/home/apps/alvin-blog/1.335791118718401552/base.py", line 195,
in error

  12.
      E 08-21 10:38PM 32.741

          self.response.out.write( template.render(errorfile,
self.template_vals))

  13.
      E 08-21 10:38PM 32.741

        File
"/base/python_lib/versions/1/google/appengine/ext/webapp/template.py", line
80, in render

  14.
      E 08-21 10:38PM 32.741

          t = load(template_path, debug)

  15.
      E 08-21 10:38PM 32.742

        File
"/base/python_lib/versions/1/google/appengine/ext/webapp/template.py", line
92, in load

  16.
      E 08-21 10:38PM 32.742

          abspath = os.path.abspath(path)

  17.
      E 08-21 10:38PM 32.742

        File "/base/python_dist/lib/python2.5/posixpath.py", line 402, in
abspath

  18.
      E 08-21 10:38PM 32.742

          if not isabs(path):

  19.
      E 08-21 10:38PM 32.742

        File "/base/python_dist/lib/python2.5/posixpath.py", line 49, in isabs

  20.
      E 08-21 10:38PM 32.742

          return s.startswith('/')

  21.
      E 08-21 10:38PM 32.743

      AttributeError: 'NoneType' object has no attribute 'startswith'



```

Original issue reported on code.google.com by `alvin.ye...@gmail.com` on 22 Aug 2009 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
default主题是有问题的,有几个文件没有,比喻error.html,
你去model.py,把class Blog里的theme_name的default改为xuming就行了.


```

Original comment by `ngn...@gmail.com` on 21 Sep 2009 at 3:33

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 1 Feb 2010 at 5:22
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 1 Feb 2010 at 5:23
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 1 Feb 2010 at 5:24
- Changed state: **Done**
