### ISSUE TITLE
我的Blog今天突然不能用了

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#132]
```
我用micolog一年多了。今天突然不能访问。
我看了AppEngine的log，写着这样的错误：
<type 'exceptions.NameError'>: global name 'g_blog' is not defined
Traceback (most recent call last):
  File "/base/data/home/apps/MY_APP_ID/1.355804491148432735/blog.py", line 730, in <module>
    main()
  File "/base/data/home/apps/MY_APP_ID/1.355804491148432735/blog.py", line 725, in main
    g_blog.application=application
我尝试将把它换到micolog2,然后能正常工作了。接着换回micolog0
.7,问题也消失了。请问是怎么回事？是否跟前几天GAE的宕机��
�关？


```

Original issue reported on code.google.com by `lynx....@gmail.com` on 17 Mar 2012 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
我也是今天出现了这个问题啊
```

Original comment by `shiqiang...@gmail.com` on 22 Aug 2012 at 3:34
