### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#134]
```
What steps will reproduce the problem?
1. deploy
2. open web
3. error 500

What is the expected output? What do you see instead?
expect to see installed micolog without error.

instead, i got this:

Error 500
Sorry, the server encountered an error. We have logged this error and will look 
into it.

Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 695, in __call__
    handler.initialize(request, response)
  File "/base/data/home/apps/s~lim-denny/1.365262127089590595/blog.py", line 55, in initialize
    archives=Archive.all().order('-year').order('-month').fetch(12)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2157, in fetch
    return list(self.run(limit=limit, offset=offset, **kwargs))
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 2326, in next
    return self.__model_class.from_entity(self.__iterator.next())
  File "/base/python_runtime/python_lib/versions/1/google/appengine/datastore/datastore_query.py", line 2892, in next
    next_batch = self.__batcher.next()
  File "/base/python_runtime/python_lib/versions/1/google/appengine/datastore/datastore_query.py", line 2754, in next
    return self.next_batch(self.AT_LEAST_ONE)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/datastore/datastore_query.py", line 2791, in next_batch
    batch = self.__next_batch.get_result()
  File "/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 604, in get_result
    return self.__get_result_hook(self)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/datastore/datastore_query.py", line 2543, in __query_result_hook
    yaml_index=yaml, xml_index=xml)
NeedIndexError: The index for this query is not ready to serve. See the 
Datastore Indexes page in the Admin Console.
The suggested index for this query is:
- kind: Archive
  properties:
  - name: year
    direction: desc
  - name: month
    direction: desc


What version of the product are you using? On what operating system?
0.74

Please provide any additional information below.


```

Original issue reported on code.google.com by `limdn...@gmail.com` on 12 Feb 2013 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
after re-deploy, the homepage is ok.
but cant access admin and get this instead:

404 Error

Sorry, we were not able to find the requested page. We have logged this error 
and will look into it.

None

```

Original comment by `limdn...@gmail.com` on 12 Feb 2013 at 10:43
