### ISSUE TITLE
mico一部署上去就报错是为啥

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#29]
```
地址:http://peigen123.appspot.com/
报错信息如下


Traceback (most recent call last):
  File "/base/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 507, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/peigen123/1.339070799807040328/blog.py", line 94, in get
    self.doget(page)
  File "/base/data/home/apps/peigen123/1.339070799807040328/base.py", line 113, in _wrapper
    method(*args, **kwargs)
  File "/base/data/home/apps/peigen123/1.339070799807040328/blog.py", line 133, in doget
    'ishome':True
  File "/base/data/home/apps/peigen123/1.339070799807040328/base.py", line 321, in render
    html=self.get_render(template_file,values)
  File "/base/data/home/apps/peigen123/1.339070799807040328/base.py", line 309, in get_render
    html = micolog_template.render(self.blog.theme, template_file, self.template_vals)
  File "/base/data/home/apps/peigen123/1.339070799807040328/micolog_template.py", line 81, in render
    return t.render(Context(template_dict))
  File "/base/data/home/apps/peigen123/1.339070799807040328/micolog_template.py", line 128, in wrap_render
    return orig_render(context)
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 168, in render
    return self.nodelist.render(context)
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 705, in render
    bits.append(self.render_node(node, context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 718, in render_node
    return(node.render(context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/loader_tags.py", line 82, in render
    return compiled_parent.render(context)
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 168, in render
    return self.nodelist.render(context)
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 705, in render
    bits.append(self.render_node(node, context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 718, in render_node
    return(node.render(context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/loader_tags.py", line 23, in render
    result = self.nodelist.render(context)
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 705, in render
    bits.append(self.render_node(node, context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 718, in render_node
    return(node.render(context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/loader_tags.py", line 96, in render
    return self.template.render(context)
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 168, in render
    return self.nodelist.render(context)
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 705, in render
    bits.append(self.render_node(node, context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 718, in render_node
    return(node.render(context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/defaulttags.py", line 122, in render
    nodelist.append(node.render(context))
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 767, in render
    output = self.filter_expression.resolve(context)
  File "/base/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 579, in resolve
    obj = func(obj, *arg_vals)
  File "/base/data/home/apps/peigen123/1.339070799807040328/filter.py", line 22, in urlencode
    return urllib.quote(value.encode('utf8'))
AttributeError: 'NoneType' object has no attribute 'encode'

转编码的时候有bug??

```

Original issue reported on code.google.com by `peigen...@gmail.com` on 10 Jan 2010 at 3:34

**Comment by GoogleCodeExporter** [comment]
```
自个hack了一下...
直接删掉filter.py的line 22 那一段
@register.filter
def urlencode(value):
    return urllib.quote(value.encode('utf8'))

也不知道会不会有别的问题.
我看源码里面,大部分用到urlencode的地方都是用base.py里面的了
,这个多余的吧?
PS:小声问一句,这个@register是干嘛的....
```

Original comment by `peigen...@gmail.com` on 10 Jan 2010 at 4:09

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 1 Feb 2010 at 5:22
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 1 Feb 2010 at 5:23
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 1 Feb 2010 at 5:24
- Changed state: **Done**
