### ISSUE TITLE
上传文件出错

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#58]
```
Traceback (most recent call last):
  File 
"/base/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 
512, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/et/1.341360345288381839/base.py", line 50, in 
wrapper
    return method(self, *args, **kwargs)
  File "/base/data/home/apps/et/1.341360345288381839/admin.py", line 906, 
in post
    Media(name = name, mtype = mtype, bits = bits).put()
  File "/base/python_lib/versions/1/google/appengine/ext/db/__init__.py", 
line 805, in put
    return datastore.Put(self._entity, rpc=rpc)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", 
line 282, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", 
line 186, in _MakeSyncCall
    rpc.check_success()
  File 
"/base/python_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", 
line 474, in check_success
    self.__rpc.CheckSuccess()
  File "/base/python_lib/versions/1/google/appengine/api/apiproxy_rpc.py", 
line 126, in CheckSuccess
    raise self.exception
RequestTooLargeError: The request to API call datastore_v3.Put() was too 
large.

是不是文件大小有限制？我大概传了3m左右的一张照片。
```

Original issue reported on code.google.com by `yim...@gmail.com` on 19 Apr 2010 at 9:37

**Comment by GoogleCodeExporter** [comment]
```
GAE限制最大1m
```

Original comment by `coolch...@gmail.com` on 20 Apr 2010 at 8:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 20 Apr 2010 at 8:06
- Changed state: **WontFix**
