### ISSUE TITLE
归档老是提示错误

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#60]
```
如下图
不知道产生原因
```

Original issue reported on code.google.com by `YISHENGG...@gmail.com` on 22 Apr 2010 at 2:38

Attachments:
- [TM截图未命名.png](https://storage.googleapis.com/google-code-attachments/micolog/issue-60/comment-0/TM截图未命名.png)
- [2.png](https://storage.googleapis.com/google-code-attachments/micolog/issue-60/comment-0/2.png)

**Comment by GoogleCodeExporter** [comment]
```
哎，我昨天也遇到这种情况了，不过我今天已经解决了，可��
�出的问题原因和你的不一样，建议你到
appengine.google.com后台看一下logs，看Debug或者Info提示什么
```

Original comment by `hongwei....@gmail.com` on 22 Apr 2010 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
<class 'google.appengine.api.urlfetch_errors.DownloadError'>: ApplicationError: 
2 
Traceback (most recent call last):
  File "/base/data/home/apps/haibolab/api2.338767517701509173/greatnewenvent.py", 
line 200, in <module>
    main()
  File "/base/data/home/apps/haibolab/api2.338767517701509173/greatnewenvent.py", 
line 197, in main
    Capture()
  File "/base/data/home/apps/haibolab/api2.338767517701509173/greatnewenvent.py", 
line 141, in Capture
    html=urllib2.urlopen(ula)
  File "/base/python_runtime/python_dist/lib/python2.5/urllib2.py", line 124, in 
urlopen
    return _opener.open(url, data)
  File "/base/python_runtime/python_dist/lib/python2.5/urllib2.py", line 381, in open
    response = self._open(req, data)
  File "/base/python_runtime/python_dist/lib/python2.5/urllib2.py", line 399, in 
_open
    '_open', req)
  File "/base/python_runtime/python_dist/lib/python2.5/urllib2.py", line 360, in 
_call_chain
    result = func(*args)
  File "/base/python_runtime/python_dist/lib/python2.5/urllib2.py", line 1107, in 
http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/base/python_runtime/python_dist/lib/python2.5/urllib2.py", line 1080, in 
do_open
    r = h.getresponse()
  File "/base/python_runtime/python_dist/lib/python2.5/httplib.py", line 197, in 
getresponse
    self._allow_truncated, self._follow_redirects)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py", 
line 241, in fetch
    return rpc.get_result()
  File 
"/base/python_runtime/python_lib/versions/1/google/appengine/api/apiproxy_stub_m
ap.py
", line 501, in get_result
    return self.__get_result_hook(self)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/api/urlfetch.py", 
line 325, in _get_fetch_result
    raise DownloadError(str(err))
W 04-22 07:11AM 39.108
This request caused a new process to be started for your application, and thus 
caused 
your application code to be loaded for the first time. This request may thus 
take 
longer and use more CPU than a typical request for your application.
```

Original comment by `YISHENGG...@gmail.com` on 22 Apr 2010 at 3:12

**Comment by GoogleCodeExporter** [comment]
```
你贴你更新归档的错误
大概上面显示的是 admin/do/update_archives 
Trace Back ....
后面的
```

Original comment by `holy...@hotmail.com` on 22 Apr 2010 at 3:18

**Comment by GoogleCodeExporter** [comment]
```
这个有解决办法吗？
```

Original comment by `YISHENGG...@gmail.com` on 22 Apr 2010 at 3:20

**Comment by GoogleCodeExporter** [comment]
```
不好意思
上面的好像贴错了
我的博客程序的日志里面没看到相关的报错
```

Original comment by `YISHENGG...@gmail.com` on 22 Apr 2010 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
fixed r122
```

Original comment by `coolch...@gmail.com` on 4 May 2010 at 8:14
- Changed state: **Fixed**
