### ISSUE TITLE
这个是什么情况啊? 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#87]
```
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 511, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/shanggangw/1.343074048954217605/blog.py", line 95, in get
    self.doget(page)
  File "/base/data/home/apps/shanggangw/1.343074048954217605/base.py", line 89, in _wrapper
    method(*args, **kwargs)
  File "/base/data/home/apps/shanggangw/1.343074048954217605/blog.py", line 130, in doget
    'ishome':True
  File "/base/data/home/apps/shanggangw/1.343074048954217605/base.py", line 328, in render
    html=self.get_render(template_file,values)
  File "/base/data/home/apps/shanggangw/1.343074048954217605/base.py", line 316, in get_render
    html = micolog_template.render(self.blog.theme, template_file, self.template_vals)
  File "/base/data/home/apps/shanggangw/1.343074048954217605/micolog_template.py", line 81, in render
    return t.render(Context(template_dict))
  File "/base/data/home/apps/shanggangw/1.343074048954217605/micolog_template.py", line 128, in wrap_render
    return orig_render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 168, in render
    return self.nodelist.render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 705, in render
    bits.append(self.render_node(node, context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 718, in render_node
    return(node.render(context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/loader_tags.py", line 82, in render
    return compiled_parent.render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 168, in render
    return self.nodelist.render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 705, in render
    bits.append(self.render_node(node, context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 718, in render_node
    return(node.render(context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/loader_tags.py", line 23, in render
    result = self.nodelist.render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 705, in render
    bits.append(self.render_node(node, context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 718, in render_node
    return(node.render(context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/loader_tags.py", line 96, in render
    return self.template.render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 168, in render
    return self.nodelist.render(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 705, in render
    bits.append(self.render_node(node, context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 718, in render_node
    return(node.render(context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/defaulttags.py", line 122, in render
    nodelist.append(node.render(context))
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 767, in render
    output = self.filter_expression.resolve(context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 563, in resolve
    obj = resolve_variable(self.var, context)
  File "/base/python_runtime/python_lib/versions/third_party/django-0.96/django/template/__init__.py", line 650, in resolve_variable
    current = getattr(current, bits[0])
  File "/base/data/home/apps/shanggangw/1.343074048954217605/model.py", line 260, in count
    return self.posts.count()
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 1717, in count
    result = raw_query.Count(limit=limit, rpc=rpc)
  File "/base/python_runtime/python_lib/versions/1/google/appengine/api/datastore.py", line 1278, in Count
    raise _ToDatastoreError(err)
NeedIndexError: The built-in indices are not efficient enough for this query 
and your data. Please add a composite index for this query.

```

Original issue reported on code.google.com by `YISHENGG...@gmail.com` on 25 Jul 2010 at 4:08

**Comment by GoogleCodeExporter** [comment]
```
开始使用时好好的,我rpc传了很多资料上去 
结果就报错了,主页无法进入,admin可以进去,按?p=0000X直接进入�
��面只能进error页面 其他的都报错,
不知道是什么原因?
```

Original comment by `YISHENGG...@gmail.com` on 26 Jul 2010 at 12:28

**Comment by GoogleCodeExporter** [comment]
```
找到原因了 原来是查询1000的限制, 
目录count数超过1000了,把模板里面的sidder.html的count去掉就行了
```

Original comment by `YISHENGG...@gmail.com` on 26 Jul 2010 at 1:35

**Comment by GoogleCodeExporter** [comment]
```
找到原因了 原来是查询1000的限制, 
目录count数超过1000了,把模板里面的sidder.html的count去掉就行了
```

Original comment by `YISHENGG...@gmail.com` on 26 Jul 2010 at 1:35
