### ISSUE TITLE
 micolog0.7rc2 尝试删除评论时候出现错误

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#89]
```
 micolog0.7rc2 当尝试在管理员界面删除评论时，出现错误，新页面提示：

Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 513, in __call__
    handler.post(*groups)
  File "/base/data/home/apps/disublog/1.343650968333866027/base.py", line 50, in wrapper
    return method(self, *args, **kwargs)
  File "/base/data/home/apps/disublog/1.343650968333866027/admin.py", line 628, in post
    comment.delit()
  File "/base/data/home/apps/disublog/1.343650968333866027/model.py", line 737, in delit
    self.entry.commentcount-=1
AttributeError: 'NoneType' object has no attribute 'commentcount'

```

Original issue reported on code.google.com by `bozi.chi...@gmail.com` on 27 Jul 2010 at 6:41

**Comment by GoogleCodeExporter** [comment]
```
0.7以前的版本，没有commentcount,所以删除会出错，只能使用Ｇ�
��Ｅ管理后台进行删除
```

Original comment by `coolch...@gmail.com` on 8 Oct 2010 at 6:25
