### ISSUE TITLE
Bug on delete parent category

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#92]
```
设置parent category之后，直接删除parent 
category，之后无法进入后台管理category页面。出错信息：
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 511, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/xiaonandiary/1.343977659710147187/base.py", line 50, in wrapper
    return method(self, *args, **kwargs)
  File "/base/data/home/apps/xiaonandiary/1.343977659710147187/admin.py", line 571, in get
    cats=Category.allTops()
  File "/base/data/home/apps/xiaonandiary/1.343977659710147187/model.py", line 318, in allTops
    return [c for c in Category.all() if not c.parent_cat]
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 3108, in __get__
    raise Error('ReferenceProperty failed to be resolved')
Error: ReferenceProperty failed to be resolved


由于我不懂python，没法修复，只好给个报告了事。。
```

Original issue reported on code.google.com by `xnxiao...@gmail.com` on 10 Aug 2010 at 6:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 8 Oct 2010 at 6:53
- Changed state: **Accepted**
